### ISSUE TITLE
Can I join your project?

### ISSUE THREAD

**Issue by HyflerSD** [y9luiz/FaceRecognitionServer#13]
Hey!, I find your project to be very interesting. I''d like to join and help! I'm a beginner level with C++ but if you need help with anything i'd be happy to assist!

**Comment by y9luiz** [comment]
Sure.

The project still under developer. 

Right now I'm just implementing the plumbing between the client and server.

If you wanna more info I can introduce more concepts to you.

Basically my goal is to have a client and a server which gonna talk with each other using a single protocol for face recognition, so the client gonna be able to send images from any kind of camera resolutions and get a response about which person is that.

**Comment by HyflerSD** [comment]
@y9luiz awesome. Let me know anything i can help you with

**Comment by y9luiz** [comment]
The current Topic that I'm working for now is the Plambing which is more related with networkimg programming that computer vision, but feel free to contribute with anything else.

Implementation list:

- Plambing between client and server;
     * Implement Aplication Message Classes;
        1 - Face Detection Message
        2 - Register User Message
        3 - Recognize User Message
     * Implement Message Receiver classe (In progress);
     * Implement Message Sender classe;
     * Integrante each one of then with the client and server module;

- Face Detection module;
- Face recognition module;
- Face recognition database manager;


What you are more interested into work on? We can have a discussion on Discord to see what fits with your objectives.

**Comment by y9luiz** [comment]
My discord username is

y9luiz#2952

Feel free to ping me.

I gonna be online tomorrow, today is a feel late here.

Have a Nice day

**Comment by HyflerSD** [comment]
request sent
